version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3003:3000"
    command: sh -c "yarn && yarn start:dev"

    depends_on:
      - redis

  redis:
    image: redis:6.2
    command: redis-server --requirepass poc
    ports:
      - "6380:6379"
